/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AFTONBLADET (https://sketchfab.com/wallander)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/darth-vader-by-makeamo-5b3371f4789c41eeaa691c9a3dfe1a96
title: Darth Vader by Makeamo
*/

import * as THREE from 'three'
import { useRef, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Darth({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/darth-transformed.glb')
  useLayoutEffect(() => {
    Object.assign(materials.Sabel_svart, {
      color: new THREE.Color('#ff2060'),
      emissive: new THREE.Color(1000, 0, 0),
      emissiveIntensity: 1000000,
      toneMapped: false
    })
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.DARTH_Sabel_vit_0.geometry} material={materials.Sabel_vit} />
          <mesh geometry={nodes.DARTH_darthvader_VaderConsolesFlickermat_0.geometry} material={materials.darthvader_VaderConsolesFlickermat} />
          <mesh geometry={nodes.DARTH_darthvader_VaderCapemat_0.geometry} material={materials.darthvader_VaderCapemat} />
          <mesh geometry={nodes.DARTH_darthvader_VaderHelmetRimmat_0.geometry} material={materials.darthvader_VaderHelmetRimmat} />
          <mesh geometry={nodes.DARTH_darthvader_VaderBodyArmourmat_0.geometry} material={materials.darthvader_VaderBodyArmourmat} />
          <mesh geometry={nodes.DARTH_Laser_0.geometry} material={materials.Laser} />
          <mesh geometry={nodes.DARTH_Sabel_svart_0.geometry} material={materials.Sabel_svart} />
          <group position={[-701.08, 246.68, 200.8]} rotation={[-0.03, 0.27, -0.2]} />
          <group position={[-200, 200, 200]} rotation={[1.18, -0.36, 0.71]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
