/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ima Gun Di (https://sketchfab.com/imagandaiii)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/anakin-40a66da73c5344e895ffdb9bc205abb3
title: Anakin
*/

import * as THREE from 'three'
import { useRef, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Jedi({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/anakin-transformed.glb')
  useLayoutEffect(() => {
    Object.values(materials).forEach((material) => {
      material.metalness = 0.85
      Object.assign(materials.light, { emissiveIntensity: 100, toneMapped: false })
      Object.assign(materials.t_hero_jedi_darthvader_cape_c, { color: new THREE.Color('white') })
    })
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.anakinsl_body0_model0_0.geometry} material={materials.head} />
        <mesh castShadow receiveShadow geometry={nodes.anakinsl_body0_model0_1.geometry} material={materials.body} />
        <mesh castShadow receiveShadow geometry={nodes.anakinsl_body1_model0_0.geometry} material={materials.t_hero_jedi_darthvader_cape_c} />
        <group position={[-3.92, 14.65, 28.26]} scale={27.66}>
          <mesh castShadow receiveShadow geometry={nodes.rfl_clone_mesh_shadow002_0.geometry} material={materials['rfl_clone_mat.002']} />
          <mesh castShadow receiveShadow geometry={nodes.rfl_clone_mesh_shadow002_1.geometry} material={materials.light} />
        </group>
        <group position={[-9.69, -12.77, 52.88]} />
        <group position={[-13.06, -33.74, 45.34]} />
        <group position={[-43.21, -30.05, 63.81]} />
        <group position={[23.47, -40.22, 10.73]} />
      </group>
    </group>
  )
}

useGLTF.preload('/anakin-transformed.glb')
