/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: 3DLadnik (https://sketchfab.com/3DLadnik)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/3d-printable-the-three-graces-58e0ae19e2984b86883edc41bf43415a
title: 3D Printable The Three Graces
*/

import { createRoot } from 'react-dom/client'
import React, { Suspense } from 'react'
import './styles.css'
import App from './App'

createRoot(document.getElementById('root')).render(
  <>
    <Suspense fallback={null}>
      <App />
    </Suspense>
    <div class="header">
      <span class="active">ART</span>
      <span>ABOUT</span>
      <span>VISIT</span>
      <span>SHOP</span>
      <span>SEARCH</span>
    </div>
    <div class="middle">
      <h2>The</h2>
      <h1>THREE GRACES</h1>
    </div>
  </>,
)
